POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2EiLCJpZCI6IjVmZDc5NzM5ZWVmMDQ0MDgyMGY3YjRmMCIsImlhdCI6MTYwNzk2NDQ3OH0.PSl6POUXRcqb9Y_SZmZQ0LV17OoIoFSLUy-Z8Z12wC4

{
    "title": "Testi",
    "author": "Nimi tähän",
    "url": "www.fi",
    "likes": 15
}
